[Constructor,
 Constructor(in string action, in string type, in string data)]
interface Intent {
  string action;
  string type;
  object data;

  void postResult(in object data);
}

[NoInterfaceObject]
interface Intents {
  const string SHARE = "http://webintents.org/share";
  const string EDIT = "http://webintents.org/edit";
  const string PICK = "http://webintents.org/pick";
  const string VIEW = "http://webintents.org/view";

  void startActivity(in Intent intent, in optional callback); 
};

Navigator implements Intents;
