Webintents::Application.routes.draw do
  match 'examples/' => 'examples#index'
  match 'examples/intents/pick/' => 'examples#pick'
  match 'examples/intents/pick/index.html' => 'examples#pick'
  match 'examples/intents/pick/action.html' => 'examples#pick_action'
  match 'examples/intents/pick/register.html' => 'examples#pick_register'
  match 'examples/intents/pick/pick.html' => 'examples#pick_pick'
  match 'examples/intents/pick/google.html' => 'examples#pick_google'
  match 'examples/intents/share/' => 'examples#share'
  match 'examples/intents/share/index.html' => 'examples#share'
  match 'examples/intents/share/register.html' => 'examples#share_register'
  match 'examples/intents/share/action.html' => 'examples#share_action'
  match 'examples/intents/share/sharelink.html' => 'examples#share_link'
  match 'examples/intents/share/shareimage.html' => 'examples#share_image'
  match 'examples/intents/shorten/index.html' => 'examples#shorten'
  match 'examples/intents/shorten/' => 'examples#shorten'
  match 'examples/intents/shorten/shorten.html' => 'examples#shorten_action'
  match 'examples/intents/discover/index.html' => 'examples#discover'
  match 'examples/intents/discover/' => 'examples#discover'
  match 'examples/intents/discover/action.html' => 'examples#discover_action'
  match 'examples/intents/discover/discover.html' => 'examples#discover_discover'
  match 'examples/usage/declarativeRegister/' => 'examples#declarative_register'
  match 'examples/usage/declarativeRegister/index.html' => 'examples#declarative_register'
  match 'examples/usage/startActivity/' => 'examples#start_activity'
  match 'examples/usage/startActivity/index.html' => 'examples#start_activity'
  match 'examples/usage/startActivityHandleInputData/' => 'examples#start_activity_handle_input_data'
  match 'examples/usage/startActivityHandleInputData/index.html' => 'examples#start_activity_handle_input_data'

  match 'faq' => 'root#faq'
  match 'discover' => 'root#discover'
  match 'share' => 'root#share'
  match 'edit' => 'root#edit'
  match 'view' => 'root#view'
  match 'pick' => 'root#pick'
  root :to => 'root#index'
end
