Webintents::Application.routes.draw do
  match 'intents/pick/' => 'examples#pick'
  match 'intents/pick/index.html' => 'examples#pick'
  match 'intents/pick/action.html' => 'examples#pick_action'
  match 'intents/pick/register.html' => 'examples#pick_register'
  match 'intents/pick/pick.html' => 'examples#pick_pick'
  match 'intents/pick/google.html' => 'examples#pick_google'
  match 'intents/share/' => 'examples#share'
  match 'intents/share/index.html' => 'examples#share'
  match 'intents/share/register.html' => 'examples#share_register'
  match 'intents/share/action.html' => 'examples#share_action'
  match 'intents/share/sharelink.html' => 'examples#share_link'
  match 'intents/share/shareimage.html' => 'examples#share_image'
  match 'intents/shorten/index.html' => 'examples#shorten'
  match 'intents/shorten/' => 'examples#shorten'
  match 'intents/shorten/shorten.html' => 'examples#shorten_action'
  match 'intents/discover/index.html' => 'examples#discover'
  match 'intents/discover/' => 'examples#discover'
  match 'intents/discover/action.html' => 'examples#discover_action'
  match 'intents/discover/discover.html' => 'examples#discover_discover'
  match 'usage/declarativeRegister/' => 'examples#declarative_register'
  match 'usage/declarativeRegister/index.html' => 'examples#declarative_register'
  match 'usage/startActivity/' => 'examples#start_activity'
  match 'usage/startActivity/index.html' => 'examples#start_activity'
  match 'usage/startActivityHandleInputData/' => 'examples#start_activity_handle_input_data'
  match 'usage/startActivityHandleInputData/index.html' => 'examples#start_activity_handle_input_data'

  root :to => 'examples#index'
end
