application: webintents-org
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /javascripts
  static_dir: javascripts

- url: /.*
  script: server.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
